project:
  type: website
  output-dir: docs

website:
  title: "Connor's Quarto Site"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - about.qmd

format:
  html:
    theme: cosmo

jupyter: python3
execute:
  eval: true
  echo: false
  warning: false
  message: false
  cache: false

