
project:
  type: website
  output-dir: docs

website:
  title: "Connor Coulter"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Assignments
        menu:
          - text: Assignment 01
            href: Assignment01/system_info.qmd
          - text: Assignment 02
            href: Assignment02/assignment2.qmd

format:
  html:
    theme: cosmo

execute:
  freeze: auto
  echo: true
  warning: false

jupyter: python3
