project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
  title: "Connor Coulter"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: journal
    toc: true
