project:
  type: website
  output-dir: _site
website:
  title: "Connor's Quarto Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
format:
  html:
    theme: cosmo
    toc: true
