name: Quarto Publish

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Debug repo state
        shell: bash
        run: |
          echo "== git config =="
          git config -l || true
          echo "== .gitmodules (if any) =="
          [ -f .gitmodules ] && cat .gitmodules || echo "no .gitmodules"
          echo "== submodule entries in index (should be empty) =="
          git ls-files -s | awk '$1==160000 {print $0}' || true
          echo "== Tree =="
          ls -la
          echo "== Quarto files =="
          ls -la _quarto.yml index.qmd about.qmd || true

      - name: Set up Python (optional)
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies (if requirements.txt exists)
        if: hashFiles('requirements.txt') != ''
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure git author for gh-pages push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Render site
        run: quarto render

      - name: Publish to gh-pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
